### ISSUE TITLE
[Error] Arrays are not supported

### ISSUE THREAD

**Issue by ilyamore88** [codex-team/hawk.webpack.plugin#22]
```
� Hawk | (⌐■_■) Sending static/js/runtime-main.b42d73a9.js.map failed: 

Arrays are not supported.
```

Error object:
```
Error: Arrays are not supported.
    at FormData.append (D:\WebStormProjects\test-react-integration\node_modules\form-data\lib\form_data.js:66:17)
    at D:\WebStormProjects\test-react-integration\node_modules\@hawk.so\webpack-plugin\src\index.js:162:14
    at async Promise.all (index 3)
```

**Comment by neSpecc** [comment]
How to reproduce?

**Comment by ilyamore88** [comment]
Deprecated
